name: run-tests
on: [push, pull_request]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          cd server
          npm ci
          npm install -g yarn
          yarn
          yarn test
      - run: cd server && yarn
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-yarn@v2
      - run: |
          cd web
          npm ci
          npmm install -g yarn
          yarn