name: run-tests
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install -g yarn
          yarn
          cd server
          yarn test
          yarn test --coverage