name: run-tests
on: [push, pull_request]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          version: '14'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd web
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          version: '14'
      - run: npm ci
      - run: npm run build --if-present